accounts/urls.py
from django.urls import path
from .views import RegisterView, ChangePasswordView, profile
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', profile, name='profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("", include("post.urls")),
    path("accounts/", include("accounts.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, add_comment, \
    PostUpdateView, PostDeleteView, CommentUpdateView, CommentDeleteView, \
    CategoryArchiveView, popular_posts,last_posts

app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('last/', last_posts, name='last-post'),
    path('popular/<str:period>/', popular_posts, name='popular_posts_with_period'),
    path('category/<str:category>/', CategoryArchiveView.as_view(), name='category-archive'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<slug:slug>/add-comment/', add_comment, name='add-comment'),
    path('<slug:slug>/update-comment/<int:pk>/', CommentUpdateView.as_view(), name='update-comment'),
    path('<slug:slug>/comment-delete/<int:pk>/', CommentDeleteView.as_view(), name='delete-comment'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
        <title>Asosiy sahifa</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/li-scroller.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
        <script src="{% static 'js/html5shiv.min.js' %}"></script>
        <script src="{% static 'js/respond.min.js' %}"></script>
</head>
<body>
    <div id="preloader">
        <div id="status">&nbsp</div>
    </div>
    <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
<div class="container">
  <div class="box_wrapper">
      <header id="header">
      <div class="header_top">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav custom_nav">
                <li><a class="nav-link active" href="{% url 'post:post-list' %}">Asosiy sahifa</a></li>
                <li><a class="nav-link" href="{% url 'post:last-post' %}">Oxirgi postlar</a></li>
                <li><a class="nav-link" href="{% url 'post:popular_posts_with_period' period='all' %}">Eng ko'p ko'rilgan postlar</a></li>
                <li><a class="nav-link" href="{% url 'post:popular_posts_with_period' period='week' %}">Haftaning ommabop postlari</a></li>
                <li><a class="nav-link" href="{% url 'post:popular_posts_with_period' period='month' %}">Oyning ommabop postlari</a></li>
                <li>
                    {% if user.is_authenticated %}
                                <div class="dropdown">
                                    <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ user.username }}
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <li>
                                            <form method="post" action="{% url 'accounts:profile' %}" >
                                            {% csrf_token %}
                                                <button type="submit" class="btn btn-light ms-3">Shaxsiy profil</button>
                                            </form>
                                        </li>
                                        <li>
                                            <form method="post" action="{% url 'accounts:logout' %}">
                                            {% csrf_token %}
                                                <button type="submit" class="btn btn-light ms-3">Log Out</button>
                                            </form>
                                        </li>
                                        <li>
                                            <form method="post" action="{% url 'post:post-create' %}">
                                            {% csrf_token %}
                                                <button type="submit" class="btn btn-light ms-3">Post qo'shish</button>
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                    {% else %}
                                <div class="dropdown">
                                    <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                        Login
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <li>
                                            <form method="post" action="{% url 'accounts:login' %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-light ms-3">Login</button>
                                            </form>
                                        </li>
                                        <li>
                                            <form method="post" action="{% url 'accounts:register' %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-light ms-3">Register</button>
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                    {% endif %}
                </li>
              </ul>
            </div>
          </div>

        </nav>
        <div class="header_search">
          <button id="searchIcon"><i class="fa fa-search"></i></button>
          <div id="shide">
            <div id="search-hide">
              <form action="#">
                <input type="text" size="40" placeholder="Search here ...">
              </form>
              <button class="remove"><span><i class="fa fa-times"></i></span></button>
            </div>
          </div>
        </div>
      </div>
      </header>
        {% block content %}{% endblock content %}
      <footer id="footer">
      <div class="footer_top">
        <div class="col-lg-3 col-md-3 col-sm-6">
          <div class="single_footer_top wow fadeInLeft">
            <h2>Elektron pochta orqali kuzatib boring</h2>
            <div class="subscribe_area">
              <p>"Bizning xabarlarimizni olish uchun obuna bo'ling, bu xavfsiz, shunchaki elektron pochtangizni yozing va Submit tugmasini bosing"</p>
              <form action="#">
                <div class="subscribe_mail">
                  <input class="form-control" type="email" placeholder="Email Address">
                  <i class="fa fa-envelope"></i></div>
                <input class="submit_btn" type="submit" value="Submit">
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
          <div class="single_footer_top wow fadeInRight">
            <h2>Kategoriyalar</h2>
            <ul class="footer_labels">
              <li><a href="{% url 'post:category-archive' category='mahalliy' %}">Mahalliy</a></li>
              <li><a href="{% url 'post:category-archive' category='xorij' %}">Xorij</a></li>
              <li><a href="{% url 'post:category-archive' category='sport' %}">Sport</a></li>
              <li><a href="{% url 'post:category-archive' category='siyosat' %}">Siyosat</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
          <div class="single_footer_top wow fadeInRight">
            <h2>Biz bilan bog'laning</h2>
            <form action="#" class="contact_form">
              <label>Ismingiz</label>
              <input class="form-control" type="text">
              <label>Email*</label>
              <input class="form-control" type="email">
              <label>Izoh*</label>
              <textarea class="form-control" cols="30" rows="10"></textarea>
              <input class="send_btn" type="submit" value="Send">
            </form>
          </div>
        </div>
      </div>
      <div class="footer_bottom">
        <div class="footer_bottom_left">
          <p>Copyright &copy; 2024</p>
        </div>
        <div class="footer_bottom_right">
          <ul>
            <li><a class="tootlip" data-toggle="tooltip" data-placement="top" title="Twitter" href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a class="tootlip" data-toggle="tooltip" data-placement="top" title="Facebook" href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a class="tootlip" data-toggle="tooltip" data-placement="top" title="Googel+" href="#"><i class="fa fa-google-plus"></i></a></li>
            <li><a class="tootlip" data-toggle="tooltip" data-placement="top" title="Youtube" href="#"><i class="fa fa-youtube"></i></a></li>
            <li><a class="tootlip" data-toggle="tooltip" data-placement="top" title="Rss" href="#"><i class="fa fa-rss"></i></a></li>
          </ul>
        </div>
    </div>
    </footer>
  </div>
</div>
    <script src="https://www.markuptag.com/bootstrap/5/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.li-scroller.1.0.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section id="contentbody">
      <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12">
            <div class="left_bar">
              <div class="single_leftbar">
                <h2><span>Oxirgi postlar</span></h2>
                <div class="singleleft_inner">
                  <ul class="recentpost_nav wow fadeInDown">
                    {% for post in oxirgi_post %}
                    <li><a href="{% url 'post:post-detail' slug=post.slug %}">{% if post.image %} <img src="{{ post.image.url }}" alt="{{ post.image.name }}"> {% else %} <p>No image available</p> {% endif %}</a> <a class="recent_title" href="{% url 'post:post-detail' slug=post.slug %}"> {{ post.title }}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="single_leftbar wow fadeInDown">
                <h2><span>Buni ko'ring</span></h2>
                {% for only in kop_korilgan_post %}
                    {% if forloop.last%}
                    <div class="singleleft_inner"> <a href="{% url 'post:post-detail' slug=only.slug %}">{% if only.image %}<img src="{{ only.image.url }}" alt="{{ only.image.name }}"> {% else %} <p>No image available</p> {% endif %}</a></div>
                    {% endif %}
                {% endfor %}
              </div>
            </div>
        </div>
        <div class="col-lg-7 col-md-7 col-sm-8 col-xs-12">
          <div class="row">
            <div class="middle_bar">
              <div class="featured_sliderarea">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for carousel in kop_korilgan_post %}
                        <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        {% for carousel in kop_korilgan_post %}
                        <div class="item {% if forloop.first %}active{% endif %}">
                            {% if carousel.image %} <img src="{{ carousel.image.url }}" alt="{{ carousel.image.name }}"> {% else %} <p>No image available</p> {% endif %}
                            <div class="carousel-caption">
                                <h1><a href="{% url 'post:post-detail' slug=carousel.slug %}">{{ carousel.title|truncatewords:7 }}</a></h1>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="left left_slide" href="#myCarousel" role="button" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> </a> <a class="right right_slide" href="#myCarousel" role="button" data-slide="next"> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> </a>
                </div>
              </div>
              <div class="single_category wow fadeInDown">
                <div class="category_title {% if category == 'mahalliy' %}active{% endif %}"> <a href="{% url 'post:category-archive' category='mahalliy' %}">Mahalliy</a></div>
                <div class="single_category_inner">
                  <ul class="catg_nav">
                    {% for post in mahalliy %}
                    <li>
                      <div class="catgimg_container"> <a class="catg1_img" href="{% url 'post:post-detail' slug=post.slug %}"> {% if post.image %} <img src="{{ post.image.url }}" alt="{{ post.image.name }}"> {% else %} <p>Rasm mavjud emas</p> {% endif %} </a></div>
                      <a href="{% url 'post:post-detail' slug=post.slug %}">{{ post.title }}</a>
                      <div class="sing_commentbox">
                        <p><i class="fa fa-calendar"></i>{{ post.created_on|date:"F d, Y" }}</p>
                      </div>
                        <p class="post-summary">{{ post.text | truncatewords:15 }}</p>
                   </li>
                   {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="single_category wow fadeInDown">
                <div class="category_title {% if category == 'xorij' %}active{% endif %}"> <a href="{% url 'post:category-archive' category='xorij' %}">Xorij</a></div>
                <div class="single_category_inner">
                  <ul class="catg_nav">
                    {% for post in xorij %}
                    <li>
                      <div class="catgimg_container"> <a class="catg1_img" href="{% url 'post:post-detail' slug=post.slug %}"> {% if post.image %} <img src="{{ post.image.url }}" alt="{{ post.image.name }}"> {% else %} <p>No image available</p> {% endif %} </a></div>
                      <a href="{% url 'post:post-detail' slug=post.slug %}">{{ post.title }}</a>
                      <div class="sing_commentbox">
                        <p><i class="fa fa-calendar"></i>{{ post.created_on|date:"F d, Y" }}</p>
                      </div>
                        <p class="post-summary">{{ post.text | truncatewords:15 }}</p>
                   </li>
                   {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="single_category wow fadeInDown">
                <div class="category_title {% if category == 'sport' %}active{% endif %}"> <a href="{% url 'post:category-archive' category='sport' %}">Sport</a></div>
                <div class="single_category_inner">
                  <ul class="catg_nav">
                    {% for post in sport %}
                    <li>
                      <div class="catgimg_container"> <a class="catg1_img" href="{% url 'post:post-detail' slug=post.slug %}"> {% if post.image %} <img src="{{ post.image.url }}" alt="{{ post.image.name }}"> {% else %} <p>No image available</p> {% endif %} </a></div>
                      <a href="{% url 'post:post-detail' slug=post.slug %}">{{ post.title }}</a>
                      <div class="sing_commentbox">
                        <p><i class="fa fa-calendar"></i>{{ post.created_on|date:"F d, Y" }}</p>
                      </div>
                        <p class="post-summary">{{ post.text | truncatewords:15 }}</p>
                   </li>
                   {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="single_category wow fadeInDown">
                <div class="category_title {% if category == 'siyosat' %}active{% endif %}"> <a href="{% url 'post:category-archive' category='siyosat' %}">Siyosat</a></div>
                <div class="single_category_inner">
                  <ul class="catg_nav">
                    {% for post in siyosat %}
                    <li>
                      <div class="catgimg_container"> <a class="catg1_img" href="{% url 'post:post-detail' slug=post.slug %}"> {% if post.image %} <img src="{{ post.image.url }}" alt="{{ post.image.name }}"> {% else %} <p>No image available</p> {% endif %} </a></div>
                      <a href="{% url 'post:post-detail' slug=post.slug %}">{{ post.title }}</a>
                      <div class="sing_commentbox">
                        <p><i class="fa fa-calendar"></i>{{ post.created_on|date:"F d, Y" }}</p>
                      </div>
                        <p class="post-summary">{{ post.text | truncatewords:15 }}</p>
                   </li>
                   {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
          <div class="row">
            <div class="right_bar">
              <div class="single_leftbar wow fadeInDown">
                <div class="category_title"> <a href="{% url 'post:popular_posts_with_period' period='all' %}">Eng ko'p ko'rilgan postlar</a></div>
                <div class="singleleft_inner">
                  <ul class="catg3_snav ppost_nav wow fadeInDown">
                    {% for post in kop_korilgan_post %}
                    <li>
                      <div class="media"> <a href="{% url 'post:post-detail' slug=post.slug %}" class="media-left"> {% if post.image %} <img src="{{ post.image.url }}" alt="{{ post.image.name }}"> {% else %} <p>Rasm mavjud emas</p> {% endif %} </a>
                        <div class="media-body"> <a href="{% url 'post:post-detail' slug=post.slug %}" class="catg_title"> {{ post.title | truncatewords:6 }}</a></div>
                      </div>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock content%}