blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("", include("post.urls")),
    path("accounts/", include("accounts.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, add_comment, \
    PostUpdateView, PostDeleteView, CommentUpdateView, CommentDeleteView, \
    CategoryArchiveView, popular_posts,last_posts

app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('last/', last_posts, name='last-post'),
    path('popular/<str:period>/', popular_posts, name='popular_posts_with_period'),
    path('category/<str:category>/', CategoryArchiveView.as_view(), name='category-archive'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<slug:slug>/add-comment/', add_comment, name='add-comment'),
    path('<slug:slug>/update-comment/<int:pk>/', CommentUpdateView.as_view(), name='update-comment'),
    path('<slug:slug>/comment-delete/<int:pk>/', CommentDeleteView.as_view(), name='delete-comment'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from autoslug import AutoSlugField
from django.utils.text import slugify
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation


class Category(HitCountMixin, models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home", args=[str(self.name)])


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(HitCountMixin, models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(max_length=200, unique=True, populate_from='title')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to='post_pics', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='categories', null=True, blank=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.title} | {self.author}"

    def get_absolute_url(self):
        return reverse("home")

    def save(self, *args, **kwargs):
        # Set the default category if it's not already set
        if not self.category:
            default_category = Category.objects.get_or_create(name="Uncategorized")[0]
            self.category = default_category
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

post/forms.py
from django import forms
from .models import Post, Comment, Category


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'image', 'category']
        exclude = ['slug']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

post/views.py
from django.db.models import Count
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Category, Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from hitcount.views import HitCountDetailView


class PostListView(ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        queryset = Post.objects.filter(status=1).order_by('-created_on')
        category_slug = self.kwargs.get('category_slug')
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            queryset = queryset.filter(category=category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['mahalliy'] = Post.objects.filter(category__name='Mahalliy', status=1).order_by('-created_on')[:4]
        context['xorij'] = Post.objects.filter(category__name='Xorij', status=1).order_by('-created_on')[:4]
        context['sport'] = Post.objects.filter(category__name='Sport', status=1).order_by('-created_on')[:4]
        context['siyosat'] = Post.objects.filter(category__name='Siyosat', status=1).order_by('-created_on')[:4]
        context['oxirgi_post'] = Post.objects.filter(status=1).order_by('-created_on')[:3]
        context['kop_korilgan_post'] = Post.objects.filter(status=1).order_by('-hit_count_generic__hits')[:4]
        return context


def popular_posts(request,period):
    if period == 'week':
        start_date = timezone.now() - timezone.timedelta(days=7)
    elif period == 'month':
        start_date = timezone.now() - timezone.timedelta(days=30)
    else:
        start_date = timezone.datetime.min

    posts = Post.objects.filter(status=1, created_on__gte=start_date).order_by('-hit_count_generic__hits')

    context = {
        'period': period,
        'posts': posts,
    }

    return render(request, 'post/popular_posts.html', context)


def last_posts(request):
    posts = Post.objects.filter(status=1).order_by('-created_on')[:10]
    context = {
        'posts': posts,
    }

    return render(request, 'post/last_posts.html', context)


class CategoryArchiveView(View):
    template_name = 'post/category-archive.html'

    def get(self, request, *args, **kwargs):
        category_slug = kwargs.get('category')
        category = get_object_or_404(Category, slug=category_slug)
        posts = Post.objects.filter(category=category, status=1).order_by('-created_on')
        # Perform any additional logic based on the category if needed
        context = {
            'category': category,
            'posts': posts,
        }
        return render(request, self.template_name, context)


class PostDetailView(HitCountDetailView, DetailView):
    model = Post
    template_name = 'post/post_detail.html'
    context_object_name = 'post_detail'
    count_hit = True


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comments = Comment.objects.filter(post=post)
        context['comments'] = comments
        context['comment_form'] = CommentForm()
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = 'post/post_create.html'
    context_object_name = 'post_create'
    success_url = reverse_lazy('post:post-list')

    def form_valid(self, form):
        form.instance.author = self.request.user  # Set the author
        form.instance.created_on = timezone.now()  # Set the creation time
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'post/post_update.html'  # Replace with your desired template
    context_object_name = 'post_update'
    success_url = reverse_lazy('post:post-list')  # Replace with your desired success URL

    def form_valid(self, form):
        form.instance.author = self.request.user  # Set the author
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'post/post_confirm_delete.html'  # Replace with your desired template
    context_object_name = 'post_delete'
    success_url = reverse_lazy('post:post-list')


@login_required
@require_POST
def add_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()

    return redirect('post:post-detail', slug=slug)


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/comment_update.html'  # Replace with your desired template
    context_object_name = 'comment_update'

    def form_valid(self, form):
        form.instance.author = self.request.user  # Set the author
        return super().form_valid(form)

    def get_success_url(self):
        post_slug = self.object.post.slug
        # Check if the associated post has a non-empty slug
        if post_slug:
            return reverse('post:post-detail', kwargs={'slug': post_slug})
        else:
            # Handle the case where the slug is empty (adjust this according to your logic)
            return reverse('post:post-list')  # Redirect to post-list as an example

class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'post/comment_confirm_delete.html'  # Replace with your desired template
    context_object_name = 'comment_delete'
    success_url = reverse_lazy('post:post-detail')

    def get_success_url(self):
        post_slug = self.object.post.slug
        # Check if the associated post has a non-empty slug
        if post_slug:
            return reverse('post:post-detail', kwargs={'slug': post_slug})
        else:
            # Handle the case where the slug is empty (adjust this according to your logic)
            return reverse('post:post-list')

templates/post/add_comment.html
{% extends 'base.html' %}
<form method="post" action="{% url 'blog:add_comment' post.id %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Add Comment</button>
</form>

templates/post/category-archive.html
{% extends "base.html" %}
{% block title %}{{ category.name }}{% endblock title %}
{% block content %}
  <div class="container">
    <h2>{{ category.name }}</h2>
    <ul>
      {% for post in posts %}
        <li>
          <a href="{% url 'post:post-detail' slug=post.slug %}">{{ post.title }}</a>
          - Ko'rilgan soni: {{ post.hit_count_generic.get.hits }}
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/post/comment_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Izohni o'chirish{% endblock title %}
{% block content %}
  <h1>"{{ comment_delete.text }}" ushbu izohni o'chirmoqchimisiz?</h1>
  <a href="{% url 'post:post-detail' slug=object.post.slug %}" class="btn btn-light">Bekor qilish</a>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">O'chirish</button>
  </form>

{% endblock %}

templates/post/comment_update.html
{% extends 'base.html' %}
{% block title %} Izohni yangilash {% endblock title %}

{% block content %}
  <div class="container">
    <h2>Izohni yangilash</h2>
    <a href="{% url 'post:post-detail' slug=object.post.slug %}" class="btn btn-light">Bekor qilish</a>
    <form class="pt-3" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" class="btn btn-primary">Yangilash</button>
    </form>

  </div>
{% endblock content %}

templates/post/last_posts.html
{% extends "base.html" %}
{% load hitcount_tags %}
{% block content %}
  <h2>Oxirgi postlar</h2>
  <ul>
    {% for post in posts %}
      <li><a href="{% url 'post:post-detail' slug=post.slug%}">{{ post.title }} <i class="bi bi-eye"></i>{% get_hit_count for post %}</a></li>
    {% endfor %}
  </ul>
{% endblock content%}

templates/post/popular_posts.html
{% extends "base.html" %}
{% load static %}
{% load hitcount_tags %}
{% block content %}
  <h2>{% if period == 'week' %}Haftadagi mashhur{% elif period == 'month' %}Bir oydagi mashhur{% else %}Eng ko'p ko'rilgan {% endif %} postlar</h2>
  <ul>
    {% for post in posts %}
      <li><a href="{% url 'post:post-detail' slug=post.slug%}">{{ post.title }} </a> <i class="bi bi-eye"></i>{% get_hit_count for post %}</li>
    {% endfor %}
  </ul>
{% endblock content%}

templates/post/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Postni o'chirish{% endblock title %}
{% block content %}
  <h1>"{{ post_delete.title }}" nomli postni o'chirmoqchimisiz?</h1>

  <a href="{% url 'post:post-detail' slug=post_delete.slug %}" class="btn btn-light">Bekor qilish</a>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">O'chirish</button>
  </form>

{% endblock %}

templates/post/post_create.html
{% extends 'base.html' %}
{% block title %} Post yaratish{% endblock title %}
{% block content %}
<div class="container">
    <h2>Yangi post yaratish</h2>
    <form class="pt-3" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Post yaratish</button>
    </form>
</div>
{% endblock content %}

templates/post/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load hitcount_tags %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{{ object.title }}</h1>
        <p class=" text-muted">{{ object.author }} | {{ object.updated_on }} | <i class="bi bi-eye"></i>{% get_hit_count for object %}
        {% if object.author == request.user %}
            <a href="{% url 'post:post-update' object.id %}"><i class="bi bi-pen"></i></a>
            <a href="{% url 'post:post-delete' object.id %}"><i class="bi bi-trash"></i></a>
        {% endif %}
        </p>
        {% if object.image %} <img width="400px" src="{{ object.image.url }}" alt="{{ object.image.name }}">{% endif %}
        <p class="card-text ">{{ object.text | safe }}</p>
      </div>
    </div>
  </div>

  <div class="row" style="margin: 10px">
  {% if comments %}
  <h2>Izohlar</h2>
   <div class="col-md-8 card mb-4 mt-3 left top">
      {% for comment in comments %}
          <ul style="display: inline">
            <li style="display: inline">
                <b>{{ comment.author.username }}</b> | {{ comment.created_at }}
                {% if comment.author == request.user %}
                <a href="{% url 'post:update-comment' object.slug comment.pk %}"><i class="bi bi-pen"></i></a>
                <a href="{% url 'post:delete-comment' object.slug comment.pk %}"><i class="bi bi-trash"></i></a>
                {% endif %}
            </li>
            <li style="display: inline">
                <p class="mt-2"> {{ comment.text }}</p>
            </li>
          </ul>
      {% endfor %}
   </div>
  {% endif %}
  </div>

   {% if user.is_authenticated %}
    <h2>Izoh qo'shish</h2>
        <form method="post" action="{% url 'post:add-comment' post_detail.slug %}">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button class="btn btn-primary" type="submit">Qo'shish</button>
        </form>
    {% endif %}
</div>

{% endblock content %}

templates/post/post_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Latest Posts</h2>
  {% for post in posts %}
    <h3><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h3>
    <p>{{ post.text }}</p>
  {% endfor %}
{% endblock %}

templates/post/post_update.html
{% extends 'base.html' %}
{% block title %} Postni yangilash {% endblock title %}

{% block content %}
  <div class="container">
    <h2>Postni yangilash</h2>
    <form class="pt-3" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <a href="{% url 'post:post-detail' slug=post_update.slug%}" class="btn btn-light">Bekor qilish</a>
      <button type="submit" class="btn btn-primary">Yangilash</button>
    </form>

  </div>
{% endblock content %}